# Generated by Django 3.1.4 on 2020-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenJean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenJogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenSneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenSunglasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenTrouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WomenWatche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
