# Generated by Django 3.1.4 on 2020-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenJean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenJogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenPolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenSneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenSunglasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenTrouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenWatche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('stock', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
